version: '3.8'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_database:/var/lib/postgres/data
    networks:
      - fullstack
  api:
    build: .
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_TABLE: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
      SSL_MODE: "disabled"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  postgres_database:

networks:
  fullstack:
    driver: bridge
